import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className="bg-white dark:bg-black">
        <h1 className="bg-white dark:bg-black dark:text-white text-center text-5xl font-bold py-10"> My app con Componente Card </h1>
        {children}
      </body>
    </html>
  );
}
